export const letters = [
{id: 1, 
    symbol: "A", 
    pattern: [true, false, false, false, false, false]}, 
{id: 2,
    symbol: "B", 
    pattern: [true, false, true, false, false, false]}, 
{id: 3,
    symbol: "C", 
    pattern: [true, true, false, false, false, false]},
{id: 4,
    symbol: "D", 
    pattern: [true, true, false, true, false, false]},
{id: 5,
    symbol: "E", 
    pattern: [true, false, false, true, false, false]},
{id: 6,
    symbol: "F", 
    pattern: [true, true, true, false, false, false]},
{id: 7,
    symbol: "G", 
    pattern: [true, true, true, true, false, false]},
{id: 8,
    symbol: "H", 
    pattern: [true, false, true, true, false, false]},
{id: 9,
    symbol: "I", 
    pattern: [false, true, true, false, false, false]},
{id: 10, 
    symbol: "J",
   pattern: [false, true, true, true, false, false]},
{id: 11, 
    symbol: "K",
   pattern: [true, false, false, false, true, false]},
{id: 12, 
    symbol: "L",
    pattern: [true, false, true, false, true, false]},
{id: 13, 
    symbol: "M",
    pattern: [true, true, false, false, true, false]},
{id: 14, 
    symbol: "N",
    pattern: [true, true, false, true, true, false]},
{id: 15, 
    symbol: "O",
    pattern: [true, false, false, true, true, false]},
{id: 16, 
    symbol: "P",
    pattern: [true, true, true, false, true, false]},
{id: 17, 
    symbol: "Q",
    pattern: [true, true, true, true, true, false]},
{id: 18, 
    symbol: "R",
    pattern: [true, false, true, true, true, false]},
{id: 19, 
    symbol: "S",
    pattern: [false, true, true, false, true, false]},
{id: 20, 
    symbol: "T",
    pattern: [false, true, true, true, true, false]},
{id: 21, 
    symbol: "U",
    pattern: [true, false, false, false, true, true]},
{id: 22, 
    symbol: "V",
    pattern: [true, false, true, false, true, true]},
{id: 23, 
    symbol: "W",
    pattern: [false, true, true, true, false, true]},
{id: 24, 
    symbol: "X",
    pattern: [true, true, false, false, true, true]},
{id: 25, 
    symbol: "Y",
    pattern: [true, true, false, true, true, true]},
 {id: 26, 
    symbol: "Z",
    pattern: [true, false, false, true, true, true]},
{id: 27, 
    symbol: "and",
    pattern: [true, true, true, false, true, true]},
{id: 28, 
    symbol: "for",
    pattern: [true, true, true, true, true, true]},
{id: 29, 
    symbol: "of",
    pattern: [true, false, true, true, true, true]},
{id: 30, 
    symbol: "the",
    pattern: [false, true, true, false, true, true]},
{id: 31, 
    symbol: "with",
    pattern: [false, true, true, true, true, true]},
{id: 32, 
    symbol: "!",
    pattern: [false, false, true, true, true, false]},
{id: 33, 
    symbol: ".",
    pattern: [false, false, true, true, false, true]},
{id: 34, 
    symbol: ",",
    pattern: [false, false, true, false, false, false]},
{id: 35, 
    symbol: ":",
    pattern: [false, false, true, true, false, false]},
{id: 36, 
    symbol: "in",
    pattern: [false, false, false, true, true, false]},
]
